### ISSUE TITLE
add error message when recursively sourced files are missing

### ISSUE THREAD

**Issue by mikaelarguedas** [colcon/colcon-bash#3]
If I delete one folder from my install directory and source the high level prefix.bash, the script throws: `bash: cd: ../new_connext_ws/install_debug_isolated/ros1_bridge: No such file or directory`.

As it stands it's unclear from the user perspective that everything else has been source properly or if the script stopped. Checking for existence before calling it and priting an error message saying notifying users that a given package has been skipped would be clearer.

Maybe this has not been done for performance purposes ?

**Comment by dirk-thomas** [comment]
Skipping the missing package would result in an incomplete environment. Potentially downstream packages might misbehave or even have errors in their setup code. Also if being used in an automated way the problem would go unnoticed (beside the warning message) which is imo undesired. Therefore I preferred to keep this case as an error.

The question here is what do you expect to happen? I would expect the user to notice the error message (maybe we can generate a custom one instead?) and then build the missing package. Otherwise sourcing the `prefix.<ext>` doesn't seem to make much sense.

**Comment by mikaelarguedas** [comment]
> Skipping the missing package would result in an incomplete environment. 

The code currently does source the following packages regardless of individual command failures doesnt it ? In that case I'm not sure how the "Potentially downstream packages might misbehave or even have errors in their setup code." issue is avoided

> The question here is what do you expect to happen? 

I expect either the script to stop and *not* source the following packages or to give a more friendly user message saying "error: This one didnt exist so will not be sourced but I'll keep sourcing the other ones".
I have a preference for the second one

**Comment by dirk-thomas** [comment]
Since you mentioned "the script throws" I read that as "the script failed". I considered that to be the desired behavior but see why you would want it to continue in your use case.

With the recent changes from #2 the `prefix.bash` script doesn't switch into each package folder and therefore doesn't print the error message anymore.

If one of the `package.bash` files is missing it currently skips that file. It only results in a message when `COLCON_TRACE=1` is being set (see https://github.com/colcon/colcon-bash/blob/24adead0f02aeb56a77ef50d7a30a655cfe69cbd/colcon_bash/shell/template/prefix.bash.em#L10-L20).

Changing the "not found" message to always being echoed (independent of `COLCON_TRACE`) as well as echoing to `1>&2` sounds fine with me. I have to check if we should only do that in the `prefix` templates or if that would also "work" in the `package` templates which are used in an automated way to setup the environment of downstream packages during the build.

**Comment by dirk-thomas** [comment]
Addressed in colcon/colcon-core#13 and the referenced PRs.
